runtime: python27
api_version: 1
threadsafe: true
service: front
handlers:

  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /
    static_dir: www

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
